#!/bin/bash

TESTDIR=$(dirname $0)

LOGDIR=$TESTDIR/../logs
mkdir -p $LOGDIR

function run {

	name=$1

	printf "%-20s" $name
	if ./$TESTDIR/$name >$LOGDIR/$name.log 2>&1; then
		echo "PASS"
	else
		echo FAIL
	fi
}

for name in $(ls $TESTDIR); do
	case $name in
	0*)	run $name;;
	esac
done
